spring:
    profiles:
        active: dev
    application:
        name: "Demo"             
        version: "0.1"            

---

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/test
        username: postgres
        password: qwerty
        driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate: 
        ddl-auto: update
      show-sql: true              
      properties:
        hibernate:
          format_sql: true
    
    config:
        activate:
            on-profile: dev
    
    # НАСТРОЙКИ ДЛЯ УМНОГО ДОМА (НОВЫЕ)
    smart-home:
      automation:
        enabled: true
        update-interval: 5000
      iot:
        mock-data: true
    
server:
    port: 8080
    servlet:
        session:
            cookie:
                same-site: none
                secure: true

jwt:
    secret: 66546A555E5A7234753778214123222A472D4B614E645262356B587032733576
    access:
        duration:
            minute: 5
            second: 300
        name: access_token
    refresh:
        duration:
            day: 7
            second: 604800
        name: refresh_token

# ЛОГИРОВАНИЕ ДЛЯ УМНОГО ДОМА
logging:
  level:
    com.example.smarthome: DEBUG
    org.hibernate.SQL: DEBUG

---

# spring:
#     config:
#         activate:
#             on-profile: prod
   